### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nathansbradshaw** [AaronAlpha/Instagram#1]
- [ ] Finish log in 
- [ ] Create working fields for Username, Email, Password working
- [ ] Activity with a list view that includes an image, username, picture, comment button and number of like.
- [ ] Child activity of previous that is triggered by tapping on the comment button, includes comments.
- [ ] Profile Activity
- [ ] Creative login screen
- [ ] Image cropping
- [ ] Email verified and account recovery 
- [ ] Image editing
- [ ] Comment the code
